<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="QueryString.aspx.cs" Inherits="LoadTestWebApp.DynamicParameters.QueryString" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<title>JavaScript dynamic property correlation sample</title> 
<script type="text/javascript" language="javascript"> 
    <!-- 
    function jScriptQueryString() {
        var Hidden = document.getElementById("HiddenFieldSessionID");
        var sessionId = Hidden.value;
        window.location = 'JScriptQuery.aspx?CustomQueryString=jScriptQueryString___' + sessionId;
    }
    //--> 
</script>
<body>
    <form id="form1" runat="server">
    <div>
        <a name="QuerystringHyperlink" href="ASPQuery.aspx?CustomQueryString=ASPQueryString___<%= Session.SessionID %>">Dynamic querystring generated by ASP.net</a> 
        <br />
        <br />
        <a href="javascript:jScriptQueryString()">Dynamic querystring generated by javascript </a>
    </div>

    <asp:HiddenField ID="HiddenFieldSessionID" runat="server" />

    </form>
</body>
</html>
